import * as React from 'react';
import Typography from '@mui/material/Typography';
import Paper from '@mui/material/Paper';
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Rating from "@mui/material/Rating";
import CardActions from "@mui/material/CardActions";
import Grid from "@mui/material/Grid";
import Divider from "@mui/material/Divider";
import "@fontsource/roboto/300.css";
import { CenterFocusStrong } from '@mui/icons-material';


const messages = [
  {
    id: 1,
    primary: "Worst Product",
    secondary: "It is the worst product I ever got. Will never recommend anyone such a bad face wash",
    person: "/public/5.jpg",
    rating: 1,
  },
  {
    id: 2,
    primary: "Perfect Product for me",
    secondary: `Most Natural FaceWash I ever got. It is made with the most rare ingredients ever. Best Money I ever spent!`,
    person: "/static/images/avatar/1.jpg",
    rating: 5,
  },
  {
    id: 3,
    primary: "Best Acne Remover",
    secondary: "It makes Acne feel better",
    person: "/static/images/avatar/2.jpg",
    rating: 3,
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
    rating: 2,
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
    rating: 3,
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
    rating: 4,
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
    rating: 1,
  },
];


export default function Comments() {
  return (
    <Paper square sx={{ pb: "50px", boxShadow: 0 }}>
      <Typography
        variant="h4"
        gutterBottom
        component="div"
        sx={{ p: 2, pb: 0,mb:2 ,fontFamily: "Arial", fontWeight: 500 }}
      >
        Customer Reviews and Ratings
      </Typography>
      <Divider sx={{mb: 4}}></Divider>

      <Grid container spacing={2}>
        {messages.map(({ id, primary, secondary, person, rating }) => (
          <Card
            sx={{
              margin: 2,
              border: 0,
              width: 300,
              borderRadius: 3,
              boxShadow: 2,
            }}
          >
            <CardContent>
              <Typography
                variant="h6"
                component="div"
                sx={{
                  fontWeight: 700,
                  mb: 2,
                  height: 40,
                  fontFamily:
                    "Roboto",
                  color:'#46474a',
                  lineHeight:'1.5'
                }}
              >
                {primary}
              </Typography>

              <Typography variant="body2" sx={{ height: 75 }}>
                {secondary}
              </Typography>
            </CardContent>
            <CardActions>
              <Rating
                name="read-only"
                value={rating}
                sx={{ mb: 2, ml: 1 }}
                readOnly
              />
            </CardActions>
          </Card>
        ))}
      </Grid>
    </Paper>
  );
}