import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Divider from "@mui/material/Divider";
import Drawer from "@mui/material/Drawer";
import IconButton from "@mui/material/IconButton";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import ReviewsOutlinedIcon from "@mui/icons-material/ReviewsOutlined";
import AddCommentOutlinedIcon from "@mui/icons-material/AddCommentOutlined";
import LightbulbOutlinedIcon from "@mui/icons-material/LightbulbOutlined";
import MenuIcon from "@mui/icons-material/Menu";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import './ResponsiveDrawer.css';
import Comments from "./comments.js";
import AISummary from "./aiSummary";
import AddReview from "./addReview";


const drawerWidth = 240;

function ResponsiveDrawer(props) {
  const messages = [
    {
      id: 1,
      primary: "Worst Product",
      secondary:
        "It is the worst product I ever got. Will never recommend anyone such a bad face wash",
      person: "/public/5.jpg",
      rating: 1.5,
    },
    {
      id: 2,
      primary: "Perfect Product for me",
      secondary: `Most Natural FaceWash I ever got. It is made with the most rare ingredients ever. Best Money I ever spent!`,
      person: "/static/images/avatar/1.jpg",
      rating: 4.9,
    },
    {
      id: 3,
      primary: "Best Acne Remover",
      secondary: "It makes Acne feel better",
      person: "/static/images/avatar/2.jpg",
      rating: 3,
    },
    {
      id: 4,
      primary: "Yes!",
      secondary: "I have the tickets to the ReactConf for this year.",
      person: "/static/images/avatar/3.jpg",
      rating: 2,
    },
    {
      id: 5,
      primary: "Doctor's Appointment",
      secondary:
        "My appointment for the doctor was rescheduled for next Saturday.",
      person: "/static/images/avatar/4.jpg",
      rating: 3,
    },
    {
      id: 6,
      primary: "Discussion",
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
      person: "/static/images/avatar/5.jpg",
      rating: 4,
    },
    {
      id: 7,
      primary: "Summer BBQ",
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
      person: "/static/images/avatar/1.jpg",
      rating: 1,
    },
  ];

  const { window } = props;
  const [mobileOpen, setMobileOpen] = React.useState(false);
  const [mainContent, setMainContent] = React.useState(
    <Comments reviews={messages} average={3.75} />
  );

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };

  const handleMenuBar = (key) => {
    if ( key  === "reviews") {
      setMainContent(<Comments reviews={messages} average={3.75}/>);
    } else if (key === "summary") {
      setMainContent(<AISummary />);
    } else if ( key  === "add") {
      setMainContent(<AddReview />);
    } 
  };


  const drawer =(
    <div>
      <Toolbar>
        <Typography
          variant="h6"
          noWrap
          component="div"
          sx={{ fontWeight: "500" }}
        >
          Herbal Facewash
        </Typography>
      </Toolbar>
      <Divider sx={{ backgroundColor: "#ffffff" }} />
      <List sx={{ elevation: 20 }}>
        <ListItem
          key="reviews"
          disablePadding
          onClick={() => handleMenuBar("reviews")}
        >
          <ListItemButton>
            <ListItemIcon>
              <ReviewsOutlinedIcon sx={{ color: "#ffffff" }} />
            </ListItemIcon>
            <ListItemText primary="Reviews" />
          </ListItemButton>
        </ListItem>

        <ListItem
          key="summary"
          disablePadding
          onClick={() => handleMenuBar("summary")}
        >
          <ListItemButton>
            <ListItemIcon>
              <LightbulbOutlinedIcon sx={{ color: "#ffffff" }} />
            </ListItemIcon>
            <ListItemText primary="AI Summary" />
          </ListItemButton>
        </ListItem>

        <ListItem key="add" disablePadding onClick={() => handleMenuBar("add")}>
          <ListItemButton>
            <ListItemIcon>
              <AddCommentOutlinedIcon sx={{ color: "#ffffff" }} />
            </ListItemIcon>
            <ListItemText primary="Add Review" />
          </ListItemButton>
        </ListItem>
      </List>
      {/* <Divider /> */}
    </div>);

  const container =
    window !== undefined ? () => window().document.body : undefined;

  return (
    <Box sx={{ display: "flex" }}>
      <CssBaseline />

      {/* Heading */}
      <AppBar
        position="fixed"
        sx={{
          width: { sm: `calc(100% - ${drawerWidth}px)` },
          display: { sm: "none" },
          ml: { sm: `${drawerWidth}px` },
          boxShadow: 0,
          backgroundColor: "#000000",
          color: "#ffffff",
        }}
      >
        <Toolbar>
          <IconButton
            color="inherit"
            aria-label="open drawer"
            edge="start"
            onClick={handleDrawerToggle}
            sx={{
              mr: 2,
              display: { sm: "none" },
              backgroundColor: "#000000",
              color: "#ffffff",
            }}
          >
            <MenuIcon/>
          </IconButton>
          <Typography
            variant="h5"
            noWrap
            component="div"
            sx={{ fontWeight: "900" }}
          >
          
          </Typography>
        </Toolbar>
      </AppBar>

      {/* MenuBar */}
      <Box
        component="nav"
        sx={{
          width: { sm: drawerWidth },
          flexShrink: { sm: 0 },
        }}
        aria-label="menu bar"
        id="menuBar"
      >
        {/* The implementation can be swapped with js to avoid SEO duplication of links. */}

        {/* Small Screen */}
        <Drawer
          container={container}
          variant="temporary"
          open={mobileOpen}
          onClose={handleDrawerToggle}
          ModalProps={{
            keepMounted: true, // Better open performance on mobile.
          }}
          sx={{
            display: { xs: "block", sm: "none" },

            "& .MuiDrawer-paper": {
              boxSizing: "border-box",
              width: drawerWidth,
              backgroundColor: "#000000",
              color: "#ffffff",
            },
          }}
        >
          {drawer}
        </Drawer>

        {/* Large Screen */}
        <Drawer
          variant="permanent"
          sx={{
            display: { xs: "none", sm: "block" },
            "& .MuiDrawer-paper": {
              boxSizing: "border-box",
              width: drawerWidth,
              backgroundColor: "#000000",
              color: "#ffffff",
            },
          }}
          open
        >
          {drawer}
        </Drawer>

      </Box>

      {/* Main Content */}
      <Box
        component="main"
        sx={{
          flexGrow: 1,
          p: 3,
          width: { sm: `calc(100% - ${drawerWidth}px)` },
        }}
      >
        <Toolbar sx={{ display: { sm: "none" } }} />
        
        {mainContent}
        
      </Box>
    </Box>
  );
}

export default ResponsiveDrawer;
